<?php
/**
 * Easytransac_Gateway payment method.
 *
 * @category    Easytransac
 * @package     Easytransac_Gateway
 * @author      Easytrasac
 * @copyright   Easytransac (https://www.easytransac.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** @var $block \Magento\Framework\View\Element\Template */
?>
<div class="block block-dashboard-saved-cards">
    <?php
    $viewModel = $block->getData('easytransac_cards');
    $ccDetails = $viewModel->getCardData();
    $count = count($ccDetails);
    ?>
    <div class="block-content">
        <?php if ($count > 0): ?>
            <div class="table-wrapper easytransac-cards">
                <table class="data table table-easytransac-cards recent" id="easytransac-cards-table">
                    <thead>
                    <tr>
                        <th class="col cctype"><?= $block->escapeHtml(__('Type')) ?></th>
                        <th class="col ccnumber"><?= $block->escapeHtml(__('Number')) ?></th>
                        <th class="col ccexpires"><?= $block->escapeHtml(__('Expires At')) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($ccDetails as $creditCard): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col cctype">
                                <?= $block->escapeHtml($creditCard['cc_type']) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Number')) ?>" class="col ccnumber">
                                <?php $endingNumber = substr($creditCard['cc_number'], 12); ?>
                                <?= $block->escapeHtml(__('ending with %1', $endingNumber)) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Expires At')) ?>" class="col ccexpires">
                                <?php $expireMonth = sprintf("%02d", $creditCard['cc_month']); ?>
                                <?= $block->escapeHtml($expireMonth . "/" . $creditCard['cc_year']) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty">
                <span><?= $block->escapeHtml(__('You have not any saved cards.')) ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
