<?php
/**
 * Easytransac_Gateway payment method.
 *
 * @category    Easytransac
 * @package     Easytransac_Gateway
 * @author      Easytrasac
 * @copyright   Easytransac (https://www.easytransac.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var $block \Easytransac\Gateway\Block\Adminhtml\System\Config\Form\NotificationUrl
 */
$url = $block->getNotificationUrl()
?>
<div>
    <strong><?= /* @noEscape */ __($url)?></strong>
</div>
